accounts:
- haloerp/accounts/*
- haloerp/controllers/accounts_controller.py
- haloerp/controllers/taxes_and_totals.py

stock:
- haloerp/stock/*
- haloerp/controllers/stock_controller.py
- haloerp/controllers/item_variant.py

assets:
- haloerp/assets/*

regional:
- haloerp/regional/*

selling:
- haloerp/selling/*
- haloerp/controllers/selling_controller.py

buying:
- haloerp/buying/*
- haloerp/controllers/buying_controller.py

support:
- haloerp/support/*

POS:
- pos*

ecommerce:
- haloerp/e_commerce/*

maintenance:
- haloerp/maintenance/*

manufacturing:
- haloerp/manufacturing/*

crm:
- haloerp/crm/*

HR:
- haloerp/hr/*

payroll:
- haloerp/payroll*

projects:
- haloerp/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['haloerp/**/*.py']
  all: ['!haloerp/**/test*.py']
